x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    tag: "{{.Name}}"

services:
  
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
    -  monitoring
    logging: *default-logging
   
volumes:
  prometheus-data:
    external: true

networks:
  monitoring:
    name: monitoring
    external: true