x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    tag: "{{.Name}}"

promtail:
  image: grafana/promtail:latest
  container_name: promtail
  volumes:
    - /opt/stacks/promtail:/etc/promtail
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock
  command: -config.file=/etc/promtail/promtail.yaml
  labels:
    logging: "promtail"
    logging_jobname: "containerlogs"
  networks:
    -  monitoring
  logging: *default-logging
   
networks:
  monitoring:
    name: monitoring
    external: true