x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    tag: "{{.Name}}"

services:  
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
      - monitoring
    logging: *default-logging

networks:
  monitoring:
    name: monitoring
    external: true

volumes:
  uptime-kuma-data:
    external: true